"""'followers'

Revision ID: 69322ab00537
Revises: 87368b795ebe
Create Date: 2020-09-11 17:07:23.246610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69322ab00537'
down_revision = '87368b795ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
