"""new fields in user model

Revision ID: 87368b795ebe
Revises: 4be6355cec9d
Create Date: 2020-09-10 11:08:41.086019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87368b795ebe'
down_revision = '4be6355cec9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
